//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Localization.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Localization.Users.UsersResources", typeof(UsersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registeration.
        /// </summary>
        public static string AccountCreateHeader {
            get {
                return ResourceManager.GetString("AccountCreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management DashBoard.
        /// </summary>
        public static string AccountDashboard {
            get {
                return ResourceManager.GetString("AccountDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Suspended.
        /// </summary>
        public static string AccountSuspended {
            get {
                return ResourceManager.GetString("AccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account has been suspended by the System Administrator.
        /// </summary>
        public static string AccountSuspendedDetails {
            get {
                return ResourceManager.GetString("AccountSuspendedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate User.
        /// </summary>
        public static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Activate User?.
        /// </summary>
        public static string ActivateUserConfirm {
            get {
                return ResourceManager.GetString("ActivateUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured while trying to Activate User..
        /// </summary>
        public static string ActivateUserError {
            get {
                return ResourceManager.GetString("ActivateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate User Done Successfully..
        /// </summary>
        public static string ActivateUserSuccess {
            get {
                return ResourceManager.GetString("ActivateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Active Directory Credintials Are Invalid..
        /// </summary>
        public static string ActiveDirectoryUserInvalidCredintials {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserInvalidCredintials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Is Not Added To The System by The System Admin..
        /// </summary>
        public static string ActiveDirectoryUserNotRegistered {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation status.
        /// </summary>
        public static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change your password?.
        /// </summary>
        public static string ChangePasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed.
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string ChangePasswordSuccessfully {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Phone.
        /// </summary>
        public static string ChangePhone {
            get {
                return ResourceManager.GetString("ChangePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation link has expired.
        /// </summary>
        public static string CodeExpiredDate {
            get {
                return ResourceManager.GetString("CodeExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Data.
        /// </summary>
        public static string CommunicationData {
            get {
                return ResourceManager.GetString("CommunicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to complete the profile.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation link expired. You must send a new link to complete the activation of your account.
        /// </summary>
        public static string ConfirmEmailCodeExpired {
            get {
                return ResourceManager.GetString("ConfirmEmailCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation link is incorrect. Make sure the mail is sent to you. You can resend a new link to activate your account if the sender does not work.
        /// </summary>
        public static string ConfirmEmailInvalidCode {
            get {
                return ResourceManager.GetString("ConfirmEmailInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been confirmed and your account has been activated.
        /// </summary>
        public static string ConfirmEmailMsg {
            get {
                return ResourceManager.GetString("ConfirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not match the confirm email.
        /// </summary>
        public static string ConfirmEmailNotMatchValidator {
            get {
                return ResourceManager.GetString("ConfirmEmailNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match the confirm password.
        /// </summary>
        public static string ConfirmPasswordNotMatchValidator {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Officer.
        /// </summary>
        public static string ContactOfficer {
            get {
                return ResourceManager.GetString("ContactOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Contry {
            get {
                return ResourceManager.GetString("Contry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string CurrentPasswordNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate User.
        /// </summary>
        public static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Deactivate User?.
        /// </summary>
        public static string DeactivateUserConfirm {
            get {
                return ResourceManager.GetString("DeactivateUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured while trying to Deactivate User..
        /// </summary>
        public static string DeactivateUserError {
            get {
                return ResourceManager.GetString("DeactivateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate User Reason.
        /// </summary>
        public static string DeactivateUserReason {
            get {
                return ResourceManager.GetString("DeactivateUserReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Deactivated Successfully..
        /// </summary>
        public static string DeactivateUserSuccess {
            get {
                return ResourceManager.GetString("DeactivateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete user?.
        /// </summary>
        public static string DeleteUserConfirm {
            get {
                return ResourceManager.GetString("DeleteUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured while trying to Delete User..
        /// </summary>
        public static string DeleteUserError {
            get {
                return ResourceManager.GetString("DeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        public static string DeleteUserSuccess {
            get {
                return ResourceManager.GetString("DeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Email.
        /// </summary>
        public static string EditMyEmail {
            get {
                return ResourceManager.GetString("EditMyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update My Profile.
        /// </summary>
        public static string EditMyProfile {
            get {
                return ResourceManager.GetString("EditMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered, please enter another email.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string EmailConfirm {
            get {
                return ResourceManager.GetString("EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not match the confirm email.
        /// </summary>
        public static string EmailConfirmNotMatchValidator {
            get {
                return ResourceManager.GetString("EmailConfirmNotMatchValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email account not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password link to my email.
        /// </summary>
        public static string EmailPasswordLink {
            get {
                return ResourceManager.GetString("EmailPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Language.
        /// </summary>
        public static string EntryLanguage {
            get {
                return ResourceManager.GetString("EntryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Speaker.
        /// </summary>
        public static string EventSpeaker {
            get {
                return ResourceManager.GetString("EventSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول&lt;br /&gt;بحساب فيسبوك.
        /// </summary>
        public static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name in Arabic.
        /// </summary>
        public static string FirstNameAr {
            get {
                return ResourceManager.GetString("FirstNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name in English.
        /// </summary>
        public static string FirstNameEn {
            get {
                return ResourceManager.GetString("FirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the link sent to your email to reset your password.
        /// </summary>
        public static string ForgetPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the activation code sent to your email to reset your password.
        /// </summary>
        public static string ForgetPasswordConfirmMsg_Email {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmMsg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the activation code sent to your mobile to reset your password.
        /// </summary>
        public static string ForgetPasswordConfirmMsg_SMS {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmMsg_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password code.
        /// </summary>
        public static string ForgotPasswordCode {
            get {
                return ResourceManager.GetString("ForgotPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name in Arabic.
        /// </summary>
        public static string FullNameAr {
            get {
                return ResourceManager.GetString("FullNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name in English.
        /// </summary>
        public static string FullNameEn {
            get {
                return ResourceManager.GetString("FullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCC Citizens.
        /// </summary>
        public static string GCC_Citizens {
            get {
                return ResourceManager.GetString("GCC_Citizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Is Required.
        /// </summary>
        public static string HospitalIsRequired {
            get {
                return ResourceManager.GetString("HospitalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Captcha Code.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Email Is Invalid.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login, please try again.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activation Status.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name in Arabic.
        /// </summary>
        public static string LastNameAr {
            get {
                return ResourceManager.GetString("LastNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name in English.
        /// </summary>
        public static string LastNameEn {
            get {
                return ResourceManager.GetString("LastNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string LoginUserTitle {
            get {
                return ResourceManager.GetString("LoginUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully signed out..
        /// </summary>
        public static string LogoutSuccessfully {
            get {
                return ResourceManager.GetString("LogoutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Roles.
        /// </summary>
        public static string ManageUserRoles {
            get {
                return ResourceManager.GetString("ManageUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name in Arabic.
        /// </summary>
        public static string MiddleNameAr {
            get {
                return ResourceManager.GetString("MiddleNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name in English.
        /// </summary>
        public static string MiddleNameEn {
            get {
                return ResourceManager.GetString("MiddleNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Already Registered for another user. please enter different phone number.
        /// </summary>
        public static string MobileAlreadyRegistered {
            get {
                return ResourceManager.GetString("MobileAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions must be approved.
        /// </summary>
        public static string MustAcceptAgreement {
            get {
                return ResourceManager.GetString("MustAcceptAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id Already Registered for another user. please enter different National Id.
        /// </summary>
        public static string NationalIdAlreadyRegistered {
            get {
                return ResourceManager.GetString("NationalIdAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user &lt;br /&gt; Join us.
        /// </summary>
        public static string NewUserJoinUs {
            get {
                return ResourceManager.GetString("NewUserJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Saudi Citizen.
        /// </summary>
        public static string NonSaudiCitizen {
            get {
                return ResourceManager.GetString("NonSaudiCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is matched with old password.
        /// </summary>
        public static string OldPasswordMatchNewPasswordValidator {
            get {
                return ResourceManager.GetString("OldPasswordMatchNewPasswordValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Coordinator.
        /// </summary>
        public static string OrganizationCoordinator {
            get {
                return ResourceManager.GetString("OrganizationCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string PasswordValidator {
            get {
                return ResourceManager.GetString("PasswordValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Already Registered for another user. please enter different phone number.
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Display Language.
        /// </summary>
        public static string PreferredUiLanguage {
            get {
                return ResourceManager.GetString("PreferredUiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful, System sent email to the user to activate his account.
        /// </summary>
        public static string RegisterationSuccess {
            get {
                return ResourceManager.GetString("RegisterationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Confirmation.
        /// </summary>
        public static string RegisterConfirmation {
            get {
                return ResourceManager.GetString("RegisterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered User.
        /// </summary>
        public static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string RegisterNewUserTitle {
            get {
                return ResourceManager.GetString("RegisterNewUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We emailed a confirmation link to your email. Click the link in that email to activate account. Make sure to check your spam box in case it got filtered.
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Code Is Required.
        /// </summary>
        public static string RequiredCaptchaMessage {
            get {
                return ResourceManager.GetString("RequiredCaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation email link.
        /// </summary>
        public static string ResendConfirmEmailLink {
            get {
                return ResourceManager.GetString("ResendConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reset Password.
        /// </summary>
        public static string ResetPasswordConfirm {
            get {
                return ResourceManager.GetString("ResetPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset password?.
        /// </summary>
        public static string ResetPasswordConfirmMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reset password. please click login link.
        /// </summary>
        public static string ResetPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password reset link. Make sure the email is sent to you. You can resend a new link to reset your password if the sender link does not work.
        /// </summary>
        public static string ResetPasswordInvalidCode {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string ResetPasswordNotValid {
            get {
                return ResourceManager.GetString("ResetPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully.
        /// </summary>
        public static string ResetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code.
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new role.
        /// </summary>
        public static string RoleCreatedSuccessfully {
            get {
                return ResourceManager.GetString("RoleCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        public static string RoleDescription {
            get {
                return ResourceManager.GetString("RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Role Discription.
        /// </summary>
        public static string RoleDescriptionArabic {
            get {
                return ResourceManager.GetString("RoleDescriptionArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Role Discription.
        /// </summary>
        public static string RoleDescriptionEnglish {
            get {
                return ResourceManager.GetString("RoleDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Role Name.
        /// </summary>
        public static string RoleNameArabic {
            get {
                return ResourceManager.GetString("RoleNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Role Name.
        /// </summary>
        public static string RoleNameEnglish {
            get {
                return ResourceManager.GetString("RoleNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Not Found in System.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SamAccountName {
            get {
                return ResourceManager.GetString("SamAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Citizen.
        /// </summary>
        public static string SaudiCitizen {
            get {
                return ResourceManager.GetString("SaudiCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save changes?.
        /// </summary>
        public static string SaveChangesConfirm {
            get {
                return ResourceManager.GetString("SaveChangesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send Confirm user email.
        /// </summary>
        public static string SendConfirmUserEmail {
            get {
                return ResourceManager.GetString("SendConfirmUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to resend Confirm User Email?.
        /// </summary>
        public static string SendConfirmUserEmailConfirm {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured while trying to send Confirm User Email.
        /// </summary>
        public static string SendConfirmUserEmailError {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm user Email is sent successfully.
        /// </summary>
        public static string SendConfirmUserEmailSuccess {
            get {
                return ResourceManager.GetString("SendConfirmUserEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation link sent.
        /// </summary>
        public static string SendedActivationLink {
            get {
                return ResourceManager.GetString("SendedActivationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Management.
        /// </summary>
        public static string SystemManagement {
            get {
                return ResourceManager.GetString("SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve the terms and conditions.
        /// </summary>
        public static string TermsAgreement {
            get {
                return ResourceManager.GetString("TermsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have to Approve Terms and Conditions.
        /// </summary>
        public static string TermsAgreementMustBeTrue {
            get {
                return ResourceManager.GetString("TermsAgreementMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name in Arabic.
        /// </summary>
        public static string ThirdNameAr {
            get {
                return ResourceManager.GetString("ThirdNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Name in English.
        /// </summary>
        public static string ThirdNameEn {
            get {
                return ResourceManager.GetString("ThirdNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Langauge Entry.
        /// </summary>
        public static string TranslatorMustSelectEntryLangauge {
            get {
                return ResourceManager.GetString("TranslatorMustSelectEntryLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Login.
        /// </summary>
        public static string TwitterLogin {
            get {
                return ResourceManager.GetString("TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update email failed.
        /// </summary>
        public static string UpdateEmailFailed {
            get {
                return ResourceManager.GetString("UpdateEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update mobile failed.
        /// </summary>
        public static string UpdateMobileFailed {
            get {
                return ResourceManager.GetString("UpdateMobileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role information updated successfully.
        /// </summary>
        public static string UpdateRoleSuccessfully {
            get {
                return ResourceManager.GetString("UpdateRoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information updated successfully.
        /// </summary>
        public static string UpdateUserSuccessfully {
            get {
                return ResourceManager.GetString("UpdateUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To resend the activation link to your e-mail, click here.
        /// </summary>
        public static string UrlActivationTitle {
            get {
                return ResourceManager.GetString("UrlActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string UserAccessDeniedMsg {
            get {
                return ResourceManager.GetString("UserAccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string UserAccessDeniedTitle {
            get {
                return ResourceManager.GetString("UserAccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account already activated.
        /// </summary>
        public static string UserAlreadyActivated {
            get {
                return ResourceManager.GetString("UserAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Can Not Be Deleted. Reason:.
        /// </summary>
        public static string UserCanNotBeDeleted {
            get {
                return ResourceManager.GetString("UserCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfully.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been locked, please contact the system administrator.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource.
        /// </summary>
        public static string UserIsNotAuthourized {
            get {
                return ResourceManager.GetString("UserIsNotAuthourized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is already registred, please select another user name.
        /// </summary>
        public static string UserNameAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserNameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Or Email.
        /// </summary>
        public static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string UserNameValidator {
            get {
                return ResourceManager.GetString("UserNameValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was deactivated by the system administrator.
        /// </summary>
        public static string UserNotActivated {
            get {
                return ResourceManager.GetString("UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found in System.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not registered with the system.
        /// </summary>
        public static string UserNotFound1 {
            get {
                return ResourceManager.GetString("UserNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Number is already registred, please enter another user Number.
        /// </summary>
        public static string UserNumberAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserNumberAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Count.
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users In Role.
        /// </summary>
        public static string UsersInRole {
            get {
                return ResourceManager.GetString("UsersInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be  between 8 and 20 english characters; must contain at least one lowercase letter, one uppercase letter, one numeric digit, one special character, cannot contain whitespace.
        /// </summary>
        public static string Validate_Password_Invalid {
            get {
                return ResourceManager.GetString("Validate_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Email Confirmation.
        /// </summary>
        public static string WaitingConfirmation {
            get {
                return ResourceManager.GetString("WaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has been sent to your email to confirm your account activation on the system please click on the link in the message to confirm your utility account.
        /// </summary>
        public static string WaitingConfirmationMessage {
            get {
                return ResourceManager.GetString("WaitingConfirmationMessage", resourceCulture);
            }
        }
    }
}
