//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Localization.PoliciesManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PoliciesManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PoliciesManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Localization.PoliciesManagement.PoliciesManagement", typeof(PoliciesManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string ApplyPolicy_Area {
            get {
                return ResourceManager.GetString("ApplyPolicy_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string ApplyPolicy_Folder {
            get {
                return ResourceManager.GetString("ApplyPolicy_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ApplyPolicy_Path {
            get {
                return ResourceManager.GetString("ApplyPolicy_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string ApplyPolicy_Policy {
            get {
                return ResourceManager.GetString("ApplyPolicy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Policy.
        /// </summary>
        public static string ApplyPolicy_Title {
            get {
                return ResourceManager.GetString("ApplyPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill policy data to create new role.
        /// </summary>
        public static string Create_FormDesc {
            get {
                return ResourceManager.GetString("Create_FormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Policy.
        /// </summary>
        public static string Create_FormTitle {
            get {
                return ResourceManager.GetString("Create_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Policy.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display policy data.
        /// </summary>
        public static string Display_FormTitle {
            get {
                return ResourceManager.GetString("Display_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Policy.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill policy data to update policy.
        /// </summary>
        public static string Edite_FormDesc {
            get {
                return ResourceManager.GetString("Edite_FormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update policy form.
        /// </summary>
        public static string Edite_FormTitle {
            get {
                return ResourceManager.GetString("Edite_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Policy.
        /// </summary>
        public static string Edite_Title {
            get {
                return ResourceManager.GetString("Edite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name.
        /// </summary>
        public static string FormPolicyName {
            get {
                return ResourceManager.GetString("FormPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string FormRoles {
            get {
                return ResourceManager.GetString("FormRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy name.
        /// </summary>
        public static string Index_List_PolicyName {
            get {
                return ResourceManager.GetString("Index_List_PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies List.
        /// </summary>
        public static string Index_ListTitle {
            get {
                return ResourceManager.GetString("Index_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert policy data for search.
        /// </summary>
        public static string Index_SearchFormDesc {
            get {
                return ResourceManager.GetString("Index_SearchFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Policy.
        /// </summary>
        public static string Index_SearchFormNewPolicyLink {
            get {
                return ResourceManager.GetString("Index_SearchFormNewPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Search Form.
        /// </summary>
        public static string Index_SearchFormTitle {
            get {
                return ResourceManager.GetString("Index_SearchFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies  List.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policy saved successfully , but you must recycle the application pool to apply the changes ..
        /// </summary>
        public static string msg_ApplyPolicy_Saved {
            get {
                return ResourceManager.GetString("msg_ApplyPolicy_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t write any spaces.
        /// </summary>
        public static string msg_DontWriteSpaces {
            get {
                return ResourceManager.GetString("msg_DontWriteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy already exists.
        /// </summary>
        public static string msg_PolicyAlreadyExist {
            get {
                return ResourceManager.GetString("msg_PolicyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Not Found in System.
        /// </summary>
        public static string msg_PolicyNotFound {
            get {
                return ResourceManager.GetString("msg_PolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least on role.
        /// </summary>
        public static string msg_SelectOneRole {
            get {
                return ResourceManager.GetString("msg_SelectOneRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after any change [add - update - delete ] you must nevigate to page [ApplyPolicies] to bind policy with pages.
        /// </summary>
        public static string msg_YouMustApplyPoliciesAfterChange {
            get {
                return ResourceManager.GetString("msg_YouMustApplyPoliciesAfterChange", resourceCulture);
            }
        }
    }
}
