//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Localization.RolesManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RolesManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RolesManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Localization.RolesManagement.RolesManagement", typeof(RolesManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill role data to create new role.
        /// </summary>
        public static string Create_FormDesc {
            get {
                return ResourceManager.GetString("Create_FormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string Create_FormTitle {
            get {
                return ResourceManager.GetString("Create_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display role data.
        /// </summary>
        public static string Display_FormTitle {
            get {
                return ResourceManager.GetString("Display_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Role.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill role data to update role.
        /// </summary>
        public static string Edite_FormDesc {
            get {
                return ResourceManager.GetString("Edite_FormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update role form.
        /// </summary>
        public static string Edite_FormTitle {
            get {
                return ResourceManager.GetString("Edite_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Role.
        /// </summary>
        public static string Edite_Title {
            get {
                return ResourceManager.GetString("Edite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string FormRoleName {
            get {
                return ResourceManager.GetString("FormRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Index_List_RoleName {
            get {
                return ResourceManager.GetString("Index_List_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles List.
        /// </summary>
        public static string Index_ListTitle {
            get {
                return ResourceManager.GetString("Index_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert role data for search.
        /// </summary>
        public static string Index_SearchFormDesc {
            get {
                return ResourceManager.GetString("Index_SearchFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string Index_SearchFormNewRoleLink {
            get {
                return ResourceManager.GetString("Index_SearchFormNewRoleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Search Form.
        /// </summary>
        public static string Index_SearchFormTitle {
            get {
                return ResourceManager.GetString("Index_SearchFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles List.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete role because it&apos;s related to policy.
        /// </summary>
        public static string msg_RoleIsRelatedToPolicy {
            get {
                return ResourceManager.GetString("msg_RoleIsRelatedToPolicy", resourceCulture);
            }
        }
    }
}
