//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Localization.SettingsManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Localization.SettingsManagement.SettingsManagement", typeof(SettingsManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Forgot Password.
        /// </summary>
        public static string AllowForgotPassword {
            get {
                return ResourceManager.GetString("AllowForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable forgot password feature.
        /// </summary>
        public static string AllowForgotPasswordDesc {
            get {
                return ResourceManager.GetString("AllowForgotPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Remember Me.
        /// </summary>
        public static string AllowRememberMe {
            get {
                return ResourceManager.GetString("AllowRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should &apos;Remember Me&apos; checkbox be displayed on login form?.
        /// </summary>
        public static string AllowRememberMeDesc {
            get {
                return ResourceManager.GetString("AllowRememberMeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Throttle Authentication.
        /// </summary>
        public static string AllowThrottleAuthentication {
            get {
                return ResourceManager.GetString("AllowThrottleAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the system throttle authentication attempts?.
        /// </summary>
        public static string AllowThrottleAuthenticationDesc {
            get {
                return ResourceManager.GetString("AllowThrottleAuthenticationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Settings.
        /// </summary>
        public static string Authentication_Title {
            get {
                return ResourceManager.GetString("Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Throttle.
        /// </summary>
        public static string AuthenticationThrottle {
            get {
                return ResourceManager.GetString("AuthenticationThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set authentication Throttle settings.
        /// </summary>
        public static string AuthenticationThrottleDesc {
            get {
                return ResourceManager.GetString("AuthenticationThrottleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set authentication general settings.
        /// </summary>
        public static string GeneralDesc {
            get {
                return ResourceManager.GetString("GeneralDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Smtp Authenticated.
        /// </summary>
        public static string IsSmtpAuthenticated {
            get {
                return ResourceManager.GetString("IsSmtpAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Time.
        /// </summary>
        public static string LockoutTime {
            get {
                return ResourceManager.GetString("LockoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of minutes to lock the user out for after specified maximum numbers..
        /// </summary>
        public static string LockoutTimeDesc {
            get {
                return ResourceManager.GetString("LockoutTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number Of Attempts.
        /// </summary>
        public static string MaximumNumberOfAttempts {
            get {
                return ResourceManager.GetString("MaximumNumberOfAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of incorrect login attempts before lockout..
        /// </summary>
        public static string MaximumNumberOfAttemptsDesc {
            get {
                return ResourceManager.GetString("MaximumNumberOfAttemptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Confirmed Account.
        /// </summary>
        public static string RequireConfirmedAccount {
            get {
                return ResourceManager.GetString("RequireConfirmedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should user confirm his account ?.
        /// </summary>
        public static string RequireConfirmedAccountDesc {
            get {
                return ResourceManager.GetString("RequireConfirmedAccountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Enable SSL.
        /// </summary>
        public static string SmtpEnableSSL {
            get {
                return ResourceManager.GetString("SmtpEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Password.
        /// </summary>
        public static string SmtpPassword {
            get {
                return ResourceManager.GetString("SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Port.
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Server.
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP settings.
        /// </summary>
        public static string SMTPSetting_Title {
            get {
                return ResourceManager.GetString("SMTPSetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set smtp settings.
        /// </summary>
        public static string SMTPSettingDesc {
            get {
                return ResourceManager.GetString("SMTPSettingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp UserName.
        /// </summary>
        public static string SmtpUserName {
            get {
                return ResourceManager.GetString("SmtpUserName", resourceCulture);
            }
        }
    }
}
