//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Localization.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Localization.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add at least one item.
        /// </summary>
        public static string AddAtleastOneItem {
            get {
                return ResourceManager.GetString("AddAtleastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add at least one speaker.
        /// </summary>
        public static string AddAtleastOneSpeaker {
            get {
                return ResourceManager.GetString("AddAtleastOneSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add at least one sponsor.
        /// </summary>
        public static string AddAtleastOneSponsor {
            get {
                return ResourceManager.GetString("AddAtleastOneSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add at least one user.
        /// </summary>
        public static string AddAtleastOneUser {
            get {
                return ResourceManager.GetString("AddAtleastOneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda Required.
        /// </summary>
        public static string AgendaRequired {
            get {
                return ResourceManager.GetString("AgendaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is added before.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add one day at least.
        /// </summary>
        public static string AtLeastOneDay {
            get {
                return ResourceManager.GetString("AtLeastOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload file Size shouldn&apos;t exceed {0}Mb.
        /// </summary>
        public static string Attachment_ErrorMessage_MaxSize {
            get {
                return ResourceManager.GetString("Attachment_ErrorMessage_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string AttachmentErrorOccured {
            get {
                return ResourceManager.GetString("AttachmentErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension not allowed. the allowed files are {0}.
        /// </summary>
        public static string AttachmentNotAllowedExtension {
            get {
                return ResourceManager.GetString("AttachmentNotAllowedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not upload file with zero size.
        /// </summary>
        public static string AttachmentSizeError {
            get {
                return ResourceManager.GetString("AttachmentSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Event Done Successfully.
        /// </summary>
        public static string CancelEventDoneSuccessfully {
            get {
                return ResourceManager.GetString("CancelEventDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel event failed.
        /// </summary>
        public static string CancelEventFailed {
            get {
                return ResourceManager.GetString("CancelEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not cancel where the maximum period of cancellation has been exceeded.
        /// </summary>
        public static string CancellationHasBeenExceeded {
            get {
                return ResourceManager.GetString("CancellationHasBeenExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this purchase request?.
        /// </summary>
        public static string CancelPurchaseRequest {
            get {
                return ResourceManager.GetString("CancelPurchaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this room request?.
        /// </summary>
        public static string CancelRoomRequest {
            get {
                return ResourceManager.GetString("CancelRoomRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Done Successfully.
        /// </summary>
        public static string ChangeDoneSuccessfully {
            get {
                return ResourceManager.GetString("ChangeDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should choose at least one item.
        /// </summary>
        public static string ChooseAtleastOneItem {
            get {
                return ResourceManager.GetString("ChooseAtleastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Required.
        /// </summary>
        public static string CommentsRequired {
            get {
                return ResourceManager.GetString("CommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count greater than  0.
        /// </summary>
        public static string CountUnvalid {
            get {
                return ResourceManager.GetString("CountUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete process completed sucessfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete event failed.
        /// </summary>
        public static string DeleteEventFailed {
            get {
                return ResourceManager.GetString("DeleteEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid discount percentage.
        /// </summary>
        public static string DiscountPercentageUnvalid {
            get {
                return ResourceManager.GetString("DiscountPercentageUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time should be greater than start time.
        /// </summary>
        public static string EndTimeGreaterStartTime {
            get {
                return ResourceManager.GetString("EndTimeGreaterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid passport or ID.
        /// </summary>
        public static string ErrorInPassportOrID {
            get {
                return ResourceManager.GetString("ErrorInPassportOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start date could not be less than or equal today.
        /// </summary>
        public static string EventStartDateLessThanToday {
            get {
                return ResourceManager.GetString("EventStartDateLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must add all days.
        /// </summary>
        public static string MustAddAllDays {
            get {
                return ResourceManager.GetString("MustAddAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must add days.
        /// </summary>
        public static string MustAddDay {
            get {
                return ResourceManager.GetString("MustAddDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date should be between the event start and end date.
        /// </summary>
        public static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid number of seats.
        /// </summary>
        public static string NumberOfSeatsUnvalid {
            get {
                return ResourceManager.GetString("NumberOfSeatsUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations imported successfully.
        /// </summary>
        public static string OrganizationsImportedSuccessfully {
            get {
                return ResourceManager.GetString("OrganizationsImportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add this range it makes overlap.
        /// </summary>
        public static string OverlapError {
            get {
                return ResourceManager.GetString("OverlapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration end date should be less than or equal event end date.
        /// </summary>
        public static string RegisterationEndLessOrEqualEventEndDate {
            get {
                return ResourceManager.GetString("RegisterationEndLessOrEqualEventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration start date should be less than or equal event end date.
        /// </summary>
        public static string RegisterationStartLessOrEqualEventEndDate {
            get {
                return ResourceManager.GetString("RegisterationStartLessOrEqualEventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration start date must be greater or equal than today.
        /// </summary>
        public static string RegisterationStartLessThanToday {
            get {
                return ResourceManager.GetString("RegisterationStartLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is sent successfully , request number {0}.
        /// </summary>
        public static string RequestSentSuceesfully {
            get {
                return ResourceManager.GetString("RequestSentSuceesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room is not avialable.
        /// </summary>
        public static string RoomIsNotAvialable {
            get {
                return ResourceManager.GetString("RoomIsNotAvialable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room seats less than event seats..
        /// </summary>
        public static string RoomSeatsLessThanEvent {
            get {
                return ResourceManager.GetString("RoomSeatsLessThanEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save process failed.
        /// </summary>
        public static string SavedFailed {
            get {
                return ResourceManager.GetString("SavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of seats now exceed the number of seats for the event.
        /// </summary>
        public static string SeatsLimit {
            get {
                return ResourceManager.GetString("SeatsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Required.
        /// </summary>
        public static string SectorRequired {
            get {
                return ResourceManager.GetString("SectorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Speaker.
        /// </summary>
        public static string SelectSpeaker {
            get {
                return ResourceManager.GetString("SelectSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sponsor Organization.
        /// </summary>
        public static string SelectSponsorOrganization {
            get {
                return ResourceManager.GetString("SelectSponsorOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sponsorship Type.
        /// </summary>
        public static string SelectSponsorshipType {
            get {
                return ResourceManager.GetString("SelectSponsorshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully signed out..
        /// </summary>
        public static string SignedOutMessage {
            get {
                return ResourceManager.GetString("SignedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid sponsoship amount.
        /// </summary>
        public static string SponsorshipAmountUnvalid {
            get {
                return ResourceManager.GetString("SponsorshipAmountUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Matched.
        /// </summary>
        public static string UserMatched {
            get {
                return ResourceManager.GetString("UserMatched", resourceCulture);
            }
        }
    }
}
