//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Localization.RulesManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RulesManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RulesManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Localization.RulesManagement.RulesManagement", typeof(RulesManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill rule data to create new rule.
        /// </summary>
        public static string Create_FormDesc {
            get {
                return ResourceManager.GetString("Create_FormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rule.
        /// </summary>
        public static string Create_FormTitle {
            get {
                return ResourceManager.GetString("Create_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Description.
        /// </summary>
        public static string FormRuleDescription {
            get {
                return ResourceManager.GetString("FormRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string FormRuleName {
            get {
                return ResourceManager.GetString("FormRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Folowed.
        /// </summary>
        public static string FormRules {
            get {
                return ResourceManager.GetString("FormRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string FormRulesName {
            get {
                return ResourceManager.GetString("FormRulesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Description.
        /// </summary>
        public static string Index_List_RulesDescription {
            get {
                return ResourceManager.GetString("Index_List_RulesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Folowed.
        /// </summary>
        public static string Index_List_RulesFolowed {
            get {
                return ResourceManager.GetString("Index_List_RulesFolowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string Index_List_RulesName {
            get {
                return ResourceManager.GetString("Index_List_RulesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules List.
        /// </summary>
        public static string Index_ListTitle {
            get {
                return ResourceManager.GetString("Index_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert rules data for search.
        /// </summary>
        public static string Index_SearchFormDesc {
            get {
                return ResourceManager.GetString("Index_SearchFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        public static string Index_SearchFormNewRuleLink {
            get {
                return ResourceManager.GetString("Index_SearchFormNewRuleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules Search From.
        /// </summary>
        public static string Index_SearchFormTitle {
            get {
                return ResourceManager.GetString("Index_SearchFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don´t write any spaces.
        /// </summary>
        public static string msg_DontWriteSpaces {
            get {
                return ResourceManager.GetString("msg_DontWriteSpaces", resourceCulture);
            }
        }
    }
}
